### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by RazvanRauta** [spryker-sdk/spryk-gui#18]
Hy,
I'm getting this error when i'm using:
` composer require --dev spryker/spryk-gui`

![image](https://user-images.githubusercontent.com/40596596/56117469-cd7ce100-5f70-11e9-99ed-6d72a3307d4a.png)

I don't have a problem connecting to git:
![image](https://user-images.githubusercontent.com/40596596/56117672-37958600-5f71-11e9-9409-eb319dae6525.png)

Any solutions?

**Comment by dereuromark** [comment]
`spryker/sdk` or `spryker/spryk-gui` do not exist, as per README and documentation please use the outlined package `spryker-sdk/spryk-gui`:

    composer require --dev spryker-sdk/spryk-gui

**Comment by RazvanRauta** [comment]
![image](https://user-images.githubusercontent.com/40596596/56118768-572dae00-5f73-11e9-9713-5dbe17ff53fc.png)

Then it should be corrected here as well:

https://documentation.spryker.com/capabilities/development/development_tools/spryk-201903.htm

Thanks it worked.

> `spryker/sdk` or `spryker/spryk-gui` do not exist, as per README and documentation please use the outlined package `spryker-sdk/spryk-gui`:
> 
> ```
> composer require --dev spryker-sdk/spryk-gui
> ```

**Comment by dereuromark** [comment]
I will forward this to the docs team. Thank you.
